"""Wave B (Fix 4) — the neutral, bytes-native generate→verify→store core.

WHY THIS LIVES HERE
-------------------
Two feature packages need to turn a reference image (or pure attributes) into a clean,
VERIFIED, person-free product image and store it:
  * app.photo_closet.generation_service — the photo cutout path (unchanged; keeps its own
    URL-based loop so its extensive monkeypatch-based tests keep intercepting).
  * app.gmail_closet.image_resolver — routes ON-MODEL email images (a person in frame)
    through generation, from raw bytes already in hand at resolve time.

Putting the shared core in the NEUTRAL app.services.image_generation layer (which imports
neither package back) lets both import it DOWNWARD, so the on-model routing does NOT create
a gmail_closet ↔ photo_closet import cycle (the cycle the P3.3 architecture note broke via
app.platform / a neutral layer). This module imports only the provider seam (same package),
the verify gate (app.gmail_closet.image_verify — an already-established services→gmail_closet
direction), storage (app.utils), and the t2i entry (lazy).

THE GUARANTEES (Fix 4)
----------------------
* MANDATORY verify: a candidate is returned ONLY when it passes the verify gate. For a
  reference-conditioned generation that is verify_generated_image (which now hard-FAILS on
  person_present — the structural "no person in the closet" backstop). For a text-to-image
  (no reference) it is verify_image PLUS an explicit person_present=false requirement.
* NEVER returns the on-model / reference original — only a freshly generated product image.
* Never raises; returns a held/budget outcome on any miss so callers fall through cleanly.

SECURITY/PRIVACY: providers receive garment bytes / attribute text only — never user
identity or order data. Steering text is fenced as untrusted (cannot force a person/scene/
logo past verify). Logs status/latency/ids only, never bytes or prompt text.
"""
from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass
from typing import Optional, Sequence, Tuple
from uuid import UUID

from app.core.config import settings
from app.gmail_closet.image_verify import (
    VerifyBudget,
    verify_generated_image,
    verify_image,
)
from app.platform.usage import UsageAccumulator
from app.services.image_generation.base import (
    GenerationBudget,
    GenerationRequest,
    get_generation_provider,
)
from app.services.image_generation.prompt import build_t2i_prompt  # noqa: F401 (re-export)

logger = logging.getLogger(__name__)

# Same live ladder as the photo path: FLUX.2 [pro] first (BFL, OFF the Gemini cap),
# nano_banana (Gemini, ON-cap) only as the verify-fail retry.
_LADDER: Tuple[str, ...] = ("flux2_pro", "nano_banana")
_SUFFIX_BY_CT = {"image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp"}


@dataclass
class GenOutcome:
    """Result of one generate→verify→store attempt (no image bytes / PII)."""
    outcome: str                     # ready | held | budget
    url: Optional[str] = None        # stored product-image URL on success
    content_sha256: Optional[str] = None
    verify_score: float = 0.0
    cost_usd: float = 0.0


def generation_armed() -> bool:
    """True when a ladder provider key AND the verify key (GEMINI_API_KEY) are present.

    Mirrors generation_service.generation_armed — callers use it to skip cleanly when
    generation isn't configured (dev without keys) rather than churn the ladder to no-ops.
    """
    from app.services.image_generation.base import list_available_providers

    available = list_available_providers()
    has_provider = any(available.get(name) for name in _LADDER)
    return has_provider and bool(settings.GEMINI_API_KEY)


def _store(storage_client, user_id: UUID, data: bytes, content_type: str) -> Optional[str]:
    """Persist verified generated bytes via content-addressed image_blobs dedup.

    Same folder as the photo generation path (generated_items/{user_id}); the dedup means
    identical bytes upload once. Returns the URL, or None if storage is unavailable."""
    if storage_client is None:
        return None
    from app.utils.image_blob_store import get_or_upload

    suffix = _SUFFIX_BY_CT.get(content_type, ".png")
    try:
        return get_or_upload(
            data,
            lambda: storage_client.upload_bytes(
                data,
                folder=f"generated_items/{user_id}",
                content_type=content_type,
                suffix=suffix,
            ),
        )
    except Exception as exc:
        logger.warning("generate_core: store failed (%s)", type(exc).__name__)
        return None


def generate_from_reference_bytes(
    *,
    reference_bytes: bytes,
    reference_content_type: str,
    name: Optional[str],
    category: Optional[str],
    color: Optional[str],
    brand: Optional[str],
    pattern: Optional[str] = None,
    storage_client,
    user_id: UUID,
    gen_budget: GenerationBudget,
    verify_budget: VerifyBudget,
    usage: UsageAccumulator,
    steering: Optional[str] = None,
    ladder: Optional[Sequence[str]] = None,
) -> GenOutcome:
    """Generate a clean product image CONDITIONED on reference bytes, verify, store.

    Bytes-native (no URL round-trip / no un-SSRF-guarded re-download): the caller passes
    the already-verified, SSRF-clean reference bytes it holds. Runs the provider ladder,
    gates EACH candidate on the MANDATORY verify_generated_image (which fails on any person
    in the candidate), stores the first pass. NEVER stores the reference itself. No DB
    writes — the caller persists the returned URL. Never raises.

    BUDGET COUNTS CALLS (cost cut #3): gen_budget.take() is consumed once per ACTUAL
    provider generation call (inside the rung loop), not once per candidate — so a ladder
    that walks N rungs costs N budget units and the per-run ceiling is a real cap on
    generation calls. Budget exhausted before any call -> 'budget'."""
    rungs = tuple(ladder or _LADDER)
    calls_made = 0
    for provider_name in rungs:
        if not gen_budget.take():
            break  # per-run generation-call ceiling hit mid-ladder
        calls_made += 1
        provider = get_generation_provider(provider_name)
        result = provider.generate(
            GenerationRequest(
                image_bytes=reference_bytes,
                content_type=reference_content_type,
                name=name,
                category=category,
                color=color,
                pattern=pattern,
                brand=brand,
                steering=steering,
            )
        )
        if result is None:
            continue  # provider failure / unavailable -> next rung
        verdict = verify_generated_image(
            reference_bytes=reference_bytes,
            reference_content_type=reference_content_type,
            candidate_bytes=result.image_bytes,
            candidate_content_type=result.content_type,
            category=category,
            color=color,
            pattern=pattern,
            name=name,
            budget=verify_budget,
            usage=usage,
        )
        # MANDATORY gate — a skipped/disabled verify is NOT a pass; person_present already
        # folded into verdict.matches=False by verify_generated_image.
        if not verdict.matches:
            continue
        url = _store(storage_client, user_id, result.image_bytes, result.content_type)
        if not url:
            break  # passed verify but storage down -> hold
        return GenOutcome(
            "ready",
            url=url,
            content_sha256=hashlib.sha256(result.image_bytes).hexdigest(),
            verify_score=float(verdict.score or 0.0),
            cost_usd=float(result.cost_usd or 0.0),
        )
    # Budget denied before we could even attempt the first rung -> 'budget' (so callers
    # treat it as capped, not as a verify miss). Any call made but no pass -> 'held'.
    return GenOutcome("budget" if calls_made == 0 else "held")


def generate_from_text(
    *,
    name: Optional[str],
    category: Optional[str],
    color: Optional[str],
    brand: Optional[str],
    storage_client,
    user_id: UUID,
    gen_budget: GenerationBudget,
    verify_budget: VerifyBudget,
    usage: UsageAccumulator,
    steering: Optional[str] = None,
) -> GenOutcome:
    """TEXT→IMAGE product image from attributes (no reference), verify, store.

    The last generation rung of the fallback ladder — used when there is no crop / no
    usable source image at all. Because there is no reference to compare against, the gate
    is the single-image verify_image PLUS an explicit no-person requirement (person_present
    must be false). NEVER raises."""
    if not gen_budget.take():
        return GenOutcome("budget")
    from app.services.image_generation.nano_banana import generate_text_to_image

    result = generate_text_to_image(build_t2i_prompt(name, category, color, brand, steering))
    if result is None:
        return GenOutcome("held")
    verdict = verify_image(
        image_bytes=result.image_bytes,
        content_type=result.content_type,
        category=category,
        color=color,
        name=name,
        budget=verify_budget,
        usage=usage,
    )
    # MANDATORY invariant gate (verify_image surfaces these but folds none of them into
    # matches — the email tiers judge REAL retailer images with different rules — so the
    # t2i caller enforces every generated-image hard gate here): expected garment/color
    # match, NO person, NO extra items, off-white background, catalog framing.
    if (
        not verdict.matches
        or verdict.person_present
        or verdict.extra_items_present
        or not verdict.background_offwhite_ok
        or not verdict.framing_ok
    ):
        return GenOutcome("held")
    url = _store(storage_client, user_id, result.image_bytes, result.content_type)
    if not url:
        return GenOutcome("held")
    return GenOutcome(
        "ready",
        url=url,
        content_sha256=hashlib.sha256(result.image_bytes).hexdigest(),
        verify_score=float(verdict.score or 0.0),
        cost_usd=float(result.cost_usd or 0.0),
    )


# Photo-seam Phase 2: build_t2i_prompt moved to app.services.image_generation.prompt so
# the t2i prompt embeds the SAME INVARIANT_BLOCK as the reference prompt (one invariant
# definition, every entry point). Re-exported here for existing importers.
