"""image_status 'held': resolved image on a variant-named row, deck-review only

Revision ID: 0041_image_status_held
Revises: 0040_receipt_document
Create Date: 2026-07-10

Gate-2 close-out defect fix: needs_enrichment previously keyed off the CREATING
email kind, so a confirmation line rendered as manifest variant text ("SIZE: Baby
Blue-one-size QTY: 1") bypassed the generation exclusion and could reach 'ready'
with a search-resolved image verified only against category+color. Such images are
plausible-but-unconfirmed. 'held' marks them: image kept attached for deck review,
row flagged needs_enrichment, nothing auto-accepts it.

Retro-flags the affected rows: gmail rows at 'ready' whose name carries manifest
furniture get needs_enrichment=true + image_status='held' (image_url untouched).
"""
from alembic import op

revision = "0041_image_status_held"
down_revision = "0040_receipt_document"
branch_labels = None
depends_on = None


UPGRADE_SQL = r"""
-- The live table carries BOTH the ORM-named CHECK and a legacy autogenerated
-- '<table>_<column>_check' twin (photo-seam Phase 4 gotcha) — drop both.
ALTER TABLE public.ingest_candidates DROP CONSTRAINT IF EXISTS image_status;
ALTER TABLE public.ingest_candidates DROP CONSTRAINT IF EXISTS ingest_candidates_image_status_check;
ALTER TABLE public.ingest_candidates ADD CONSTRAINT image_status CHECK (
    image_status IS NULL OR image_status IN
    ('resolved','placeholder','pending','user_uploaded','held'));

-- Retro-flag: ready gmail rows whose canonical name is manifest variant text.
UPDATE public.ingest_candidates
SET needs_enrichment = true,
    image_status = 'held'
WHERE source_type = 'gmail'
  AND pipeline_state = 'ready'
  AND (name ~* '^\s*size\s*:' OR name ~* 'qty\s*:?\s*\d+\s*$');
"""

DOWNGRADE_SQL = r"""
UPDATE public.ingest_candidates
SET image_status = 'resolved'
WHERE image_status = 'held';
ALTER TABLE public.ingest_candidates DROP CONSTRAINT IF EXISTS image_status;
ALTER TABLE public.ingest_candidates DROP CONSTRAINT IF EXISTS ingest_candidates_image_status_check;
ALTER TABLE public.ingest_candidates ADD CONSTRAINT image_status CHECK (
    image_status IS NULL OR image_status IN
    ('resolved','placeholder','pending','user_uploaded'));
"""


def upgrade() -> None:
    op.execute(UPGRADE_SQL)


def downgrade() -> None:
    op.execute(DOWNGRADE_SQL)
