"""clothing_items cutout_url + cutout_status: true-alpha mattes, matted once at birth

Revision ID: 0042_item_cutouts
Revises: 0041_image_status_held
Create Date: 2026-07-11

Collage Phase 1 (per the collage-quality spike, COLLAGE_QUALITY_SPIKE.md): the
collage previously re-derived a cutout per RENDER with a color-tolerance key that
structurally cannot matte white/light garments on the near-white invariant
background. Each item now gets a true-alpha cutout matted ONCE (local u2net ONNX,
QA-gated) at the confirm chokepoint / by the backfill script:

  cutout_url    — the stored item_cutouts/{user_id}/ PNG (NULL until matted)
  cutout_status — NULL   = never matted (backfill target)
                  'ready'    = cutout_url holds the QA-passed matte
                  'no_matte' = QA gate refused; the collage renders this item
                               FLAT on its own tile, never a patchy rectangle

Additive only (nullable columns, no rewrite, no backfill here — the backfill is
the resumable scripts/backfill_cutouts.py, not a migration). The CHECK follows
the photo-seam Phase 4 gotcha: drop BOTH possible names before adding.
"""
from alembic import op

revision = "0042_item_cutouts"
down_revision = "0041_image_status_held"
branch_labels = None
depends_on = None


UPGRADE_SQL = r"""
ALTER TABLE public.clothing_items ADD COLUMN IF NOT EXISTS cutout_url TEXT NULL;
ALTER TABLE public.clothing_items ADD COLUMN IF NOT EXISTS cutout_status TEXT NULL;

-- ORM-named CHECK + potential autogenerated twin (photo-seam Phase 4 gotcha).
ALTER TABLE public.clothing_items DROP CONSTRAINT IF EXISTS cutout_status;
ALTER TABLE public.clothing_items DROP CONSTRAINT IF EXISTS clothing_items_cutout_status_check;
ALTER TABLE public.clothing_items ADD CONSTRAINT cutout_status CHECK (
    cutout_status IS NULL OR cutout_status IN ('ready','no_matte'));
"""

DOWNGRADE_SQL = r"""
ALTER TABLE public.clothing_items DROP CONSTRAINT IF EXISTS cutout_status;
ALTER TABLE public.clothing_items DROP CONSTRAINT IF EXISTS clothing_items_cutout_status_check;
ALTER TABLE public.clothing_items DROP COLUMN IF EXISTS cutout_status;
ALTER TABLE public.clothing_items DROP COLUMN IF EXISTS cutout_url;
"""


def upgrade() -> None:
    op.execute(UPGRADE_SQL)


def downgrade() -> None:
    op.execute(DOWNGRADE_SQL)
